export const UPDATE_SELECTED_MONTH = 'UPDATE_SELECTED_MONTH';

export const FETCH_MONTH_BEGIN = 'FETCH_MONTH_BEGIN';
export const FETCH_MONTH_SUCCESS = 'FETCH_MONTH_SUCCESS';
export const FETCH_MONTH_ERROR = 'FETCH_MONTH_ERROR';

export const ADD_APPOINTMENT_BEGIN = 'ADD_APPOINTMENT_BEGIN';
export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS';
export const ADD_APPOINTMENT_ERROR = 'ADD_APPOINTMENT_ERROR';
