export const UPDATE_SELECTED_MONTH = 'UPDATE_SELECTED_MONTH';

export const FETCH_MONTH_BEGIN = 'FETCH_MONTH_BEGIN';
export const FETCH_MONTH_SUCCESS = 'FETCH_MONTH_SUCCESS';
export const FETCH_MONTH_ERROR = 'FETCH_MONTH_ERROR';
