export const UPDATE_SELECTED_MONTH = 'UPDATE_SELECTED_MONTH';

export const FETCH_MONTH_BEGIN = 'FETCH_MONTH_BEGIN';
export const FETCH_MONTH_SUCCESS = 'FETCH_MONTH_SUCCESS';
export const FETCH_MONTH_ERROR = 'FETCH_MONTH_ERROR';

export const ADD_APPOINTMENT_BEGIN = 'ADD_APPOINTMENT_BEGIN';
export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS';
export const ADD_APPOINTMENT_ERROR = 'ADD_APPOINTMENT_ERROR';

export const DELETE_APPOINTMENT_BEGIN = 'DELETE_APPOINTMENT_BEGIN';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_ERROR = 'DELETE_APPOINTMENT_ERROR';

export const EDIT_APPOINTMENT_BEGIN = 'EDIT_APPOINTMENT_BEGIN';
export const EDIT_APPOINTMENT_SUCCESS = 'EDIT_APPOINTMENT_SUCCESS';
export const EDIT_APPOINTMENT_ERROR = 'EDIT_APPOINTMENT_ERROR';

export const RESET_APPOINTMENTS = 'RESET_APPOINTMENTS';
