export const FETCH_STATISTICS_BEGIN = 'FETCH_STATISTICS_BEGIN';
export const FETCH_STATISTICS_SUCCESS = 'FETCH_STATISTICS_SUCCESS';
export const FETCH_STATISTICS_ERROR = 'FETCH_STATISTICS_ERROR';

export const RESET_STATISTICS = 'RESET_STATISTICS';
